[book]
title = "Grounds"
authors = ["Bojan Rajkovic"]
language = "en"

[build]
build-dir = "book"

[preprocessor.validator]
command = "mdbook-validator"

[preprocessor.validator.validators.typescript]
# Custom container with @grounds/* packages pre-installed
# Build with: ./docs/build-validator.sh
container = "grounds-example-validator:latest"
script = "validators/validate-typescript.sh"
